//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMSN.DATA.BranchManagerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BranchManager
    {
        public int Id { get; set; }
        public string Region { get; set; }
        public string BranchName { get; set; }
        public Nullable<int> BranchCode { get; set; }
        public string FullName { get; set; }
        public string MobileNo { get; set; }
    }
}
